version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ai_assistant_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai_assistant}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_assistant_api
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-ai_assistant}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      UPLOAD_DIR: ${UPLOAD_DIR:-/data/uploads}
    ports:
      - "8000:8000"
    volumes:
      - upload_data:/data/uploads
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app

volumes:
  postgres_data:
  upload_data:

